apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pods
  # strategy: RollingUpdate
  template:
    metadata:
      labels:
        app: backend-pods
    spec:
      containers:
      - name: clinic-backend-app
        image: ahmeddalii/clinic-backend:2.0
        env:        
        - name: BACKEND_URL
          value: '0.0.0.0' 
        - name: BACKEND_SERVER_PORT
          value: '5000'      
        - name: DB_USER
          value: 'ahmed'
        - name: DB_PASS
          value: '123'
        - name: DB_NAME
          value: 'clinicdb'
        - name: DB_HOST
          value: '172.30.1.220'
        - name: MQ_HOST
          value: '172.30.72.169'
       
