# Backend Containerfile

FROM registry.redhat.io/rhel8/python-311

LABEL description="Clinic Backend image"

ENV BACKEND_SERVER_PORT=5000

EXPOSE $BACKEND_SERVER_PORT

RUN pip install flask==2.3.3 flask-mysql flask-cors pika

COPY ./clinic-reservation-system/ /opt/source-code	

# ENTRYPOINT FLASK_APP=/opt/source-code/app.py flask run

WORKDIR /opt/source-code

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]




